version: '3.8'

services:

  mysql:
   container_name: tntconcept-mysql
   image: mysql:8.0.32
   ports:
    - "3306:3306"
   command: ["--log_bin_trust_function_creators=1"]
   tmpfs:
     - /var/lib/mysql
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: tntconcept
     MYSQL_USER: tntconcept
     MYSQL_PASSWORD: tntconcept
