micronaut:
  application:
    name: tntconcept-api

  server:
    thread-selection: IO

    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:3000
          allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowedHeaders:
            - Content-Type

    multipart:
      max-file-size: 10485760

  router:
    static-resources:
      default:
        enabled: false

  security:
    basic-auth:
      enabled: false
    authentication: cookie

    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '${TNT_TOKEN_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne_nzp9g9QiAqE8L9VsKuTX!v4WVWqX}'
              jws-algorithm: HS256
        generator:
          access-token:
            expiration: 3600
          refresh-token:
            secret: '${TNT_REFRESH_TOKEN_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne_kLWc@fTf!TDgZ-NuymUTkCX.jCB4}'
      refresh:
        cookie:
          cookie-http-only: true

    oauth2:
      clients:
        google:
          client-id: '${TNT_OAUTH_CLIENT_ID:oauth_client_id}'
          client-secret: '${TNT_OAUTH_CLIENT_SECRET:oauth_client_secret}'
          openid:
            issuer: 'https://accounts.google.com'
            authorization:
              prompt: select_account
      callback-uri: 'http://localhost:8080/oauth/callback/google'
      endpoints:
        logout:
          get-allowed: true

    redirect:
      login-success: 'http://localhost:3000/tnt/binnacle'

    intercept-url-map:
      - pattern: /api-hook/**
        access:
          - isAnonymous()
      - pattern: /
        access:
          - isAnonymous()
      - pattern: /api/version
        access:
          - isAnonymous()
      - pattern: /oauth/login/google
        access:
          - isAnonymous()
      - pattern: /oauth/callback/google
        access:
          - isAnonymous()
      - pattern: /**
        access:
          - isAuthenticated()

jackson:
  serialization-inclusion: always
  serialization:
    writeDatesAsTimestamps: false

datasources:
  default:
    db-type: mysql
    dialect: MYSQL
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${TNT_DB_HOST:localhost}:${TNT_DB_PORT:3306}/${TNT_DB_DATABASE:tntconcept}?autoReconnect=true
    username: ${TNT_DB_USERNAME:tntconcept}
    password: ${TNT_DB_PASSWORD:tntconcept}
    minimumIdle: 1
    maximumPoolSize: 100

flyway:
  datasources:
    default:

jpa:
  default:
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true
        physical_naming_strategy: 'org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl'
    entity-scan:
      packages: 'com.autentia.tnt.binnacle.entities'

javamail:
  enabled: true
  authentication:
    username: '${TNT_MAIL_USERNAME:mailserver_username}'
    password: '${TNT_MAIL_PASSWORD:mailserver_password}'
  properties:
    mail.transport.protocol: smtp
    mail.host: smtp.gmail.com
    mail.port: 465
    mail.auth: true
    mail:
      smtp:
        starttls:
          enable: true

app:
  version: '@project.version@'

  files:
    activity-images: '/tmp/activity/images'

  mail:
    enabled: true
    from: admin@example.com

  binnacle:
    vacations-approvers: approver@example.com
    not-workable-projects: 1

    work-summary:
      persistence-enabled: true

      # https://docs.micronaut.io/2.2.3/api/io/micronaut/scheduling/cron/CronExpression.html
      # Every day at 03:00 h UTC
      cron-expression: '0 0 3 * * ?'

      report:
        path: /tmp
        name-suffix: summary
        show-alerts-only: false

      mail:
        enabled: true
        to: ${app.binnacle.vacations-approvers}
        send-alerts-only: false
